services:
  mqtt-broker:
    build:
      context: .
      dockerfile: mosquitto/Dockerfile
    container_name: nexora-data-generator-mqtt
    environment:
      MQTT_USERNAME: ${MQTT_USERNAME:?MQTT_USERNAME is required}
      MQTT_PASSWORD: ${MQTT_PASSWORD:?MQTT_PASSWORD is required}
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-1883}:1883"
      - "${MQTT_WS_PORT:-9001}:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nexora-data-generator-backend
    depends_on:
      - mqtt-broker
    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883
      MQTT_USERNAME: ${MQTT_USERNAME:?MQTT_USERNAME is required}
      MQTT_PASSWORD: ${MQTT_PASSWORD:?MQTT_PASSWORD is required}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-*}
    restart: unless-stopped

  simulator:
    build:
      context: .
      dockerfile: simulation/Dockerfile
    container_name: nexora-data-generator-simulator
    depends_on:
      - mqtt-broker
    environment:
      MQTT_HOST: mqtt-broker
      MQTT_PORT: 1883
      MQTT_USERNAME: ${MQTT_USERNAME:?MQTT_USERNAME is required}
      MQTT_PASSWORD: ${MQTT_PASSWORD:?MQTT_PASSWORD is required}
    restart: unless-stopped
